name: andrious
description: The Andrious Solutions Website

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.44.0

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  # https://pub.dev/packages/auto_size_text/
  auto_size_text: ^3.0.0

  # https://github.com/Andrious/bazaar/
  bazaar:
    git: https://github.com/Andrious/bazaar.git
#    path: ../../examples/bazaar

  # https://pub.dev/packages/carousel_slider/
  carousel_slider: ^4.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # https://github.com/aloisdeniel/flutter_device_preview
  # https://pub.dev/packages/device_preview/
  device_preview: ^1.0.0
#    git:
#      url: https://github.com/AndriousSolutions/flutter_device_preview.git
#      ref: master
#      path: device_preview

#    path: C:/Programs/Tools/Projects/Flutter/apps/flutter_device_preview/device_preview

  # https://pub.dev/packages/easy_dynamic_theme/
  easy_dynamic_theme: ^2.0.0

  # https://pub.dev/packages/file_picker/
  file_picker: ^4.0.0

  # https://pub.dev/packages/firebase_auth/
  firebase_auth: ^3.0.0

  # https://pub.dev/packages/firebase_core/
  firebase_core: ^1.0.0

  firebase_crashlytics: ^2.0.0

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # You some HTML
  flutter_widget_from_html: ^0.8.5

  # https://pub.dev/packages/flutter_markdown/
  # Try to use this instead of auto_size_text one day
  #flutter_markdown: ^0.6.0

  # https://pub.dev/packages/gap/
  gap: ^2.0.0

  # https://pub.dev/packages/google_fonts/
  google_fonts: ^2.0.0

  # https://pub.dev/packages/google_sign_in/
  google_sign_in: ^5.0.0

  # https://pub.dev/packages/l10n_translator/
#  l10n_translator: 1.3.1

  # https://pub.dev/packages/mvc_web/
  mvc_web: ^1.0.0
#    path: ../../packages/mvc_web
  #    git:
  #      url: git://github.com/Andrious/mvc_web.git

  # https://pub.dev/packages/provider/
  provider: ^6.0.0

#  # https://github.com/mdg-iitr/scrollytell
#  scrollytell: ^1.0.0
##    path: ../../apps/scrollytell

  shrine_mvc:
    git: https://github.com/Andrious/shrine_mvc.git
#    path: ../../examples/shrine_mvc

  # https://pub.dev/packages/state_set/
  state_set: ^3.0.0
#    path: ../../packages/state_set

  # https://pub.dev/packages/easy_web_view/
#  easy_web_view: ^1.0.0

  # https://pub.dev/packages/universal_html/
  universal_html: ^2.0.0

  # https://pub.dev/packages/url_launcher/
  url_launcher: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/Montserrat-Medium.ttf
        # - asset: fonts/Montserrat-Regular.ttf
        # style: italic
    - family: Roboto
      fonts:
        - asset: fonts/roboto/Roboto-Medium.ttf
          # - asset: fonts/TrajanPro_Bold.ttf
          weight: 700

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

    - family: Electrolize
      fonts:
        - asset: fonts/Electrolize-Regular.ttf

  assets:
    - assets/i10n/i10n.csv
    - assets/images/
    - assets/images/carousel/
    - assets/images/packages/
    - assets/images/flutteruis/
    - assets/diamond.png
    - assets/slanted_menu.png
    - assets/0-0.jpg
    - assets/1-0.jpg
    - assets/2-0.jpg
    - assets/3-0.jpg
    - assets/4-0.jpg
    - assets/5-0.jpg
    - assets/6-0.jpg
    - assets/7-0.jpg
    - assets/8-0.jpg
    - assets/9-0.jpg
    - assets/10-0.jpg
    - assets/11-0.jpg
    - assets/12-0.jpg
    - assets/13-0.jpg
    - assets/14-0.jpg
    - assets/15-0.jpg
    - assets/16-0.jpg
    - assets/17-0.jpg
    - assets/18-0.jpg
    - assets/19-0.jpg
    - assets/20-0.jpg
    - assets/21-0.jpg
    - assets/22-0.jpg
    - assets/23-0.jpg
    - assets/24-0.jpg
    - assets/25-0.jpg
    - assets/26-0.jpg
    - assets/27-0.jpg
    - assets/28-0.jpg
    - assets/29-0.jpg
    - assets/30-0.jpg
    - assets/31-0.jpg
    - assets/32-0.jpg
    - assets/33-0.jpg
    - assets/34-0.jpg
    - assets/35-0.jpg
    - assets/36-0.jpg
    - assets/37-0.jpg

    - images/c1.jpg
    - images/c2.jpg
    - images/c3.jpg
    - images/c4.jpg
    - images/c5.jpg
    - images/c6.jpg
    - images/c7.jpg

    - images/facebook.png
    - images/google.png
    - images/category1.jpg
    - images/category2.jpg
    - images/products/blazer1.jpg
    - images/products/blazer2.jpg
    - images/products/dress1.jpg
    - images/products/dress2.jpg
    - images/products/hills1.jpg
    - images/products/hills2.jpg
    - images/products/jeans1.jpg
    - images/products/jeans2.jpg
    - images/products/shoe1.jpg
    - images/products/shoe2.jpg
    - images/products/skirt1.jpg
    - images/products/skirt2.jpg
    - images/products/tshirt1.jpg
    - images/products/tshirt2.jpg
    - images/recentImages/blazer1.jpeg
    - images/recentImages/dress1.jpeg
    - images/recentImages/dress2.jpeg
    - images/recentImages/hills1.jpeg
    - images/recentImages/skt1.jpeg
    - images/sunny.png
    - images/moon.png

    - images/logos/github.png
    - images/logos/linkedin.png
    - images/logos/twitter.png
    - images/logos/appstore_dark.png
    - images/logos/appstore_light.png
    - images/logos/googleplay_dark.png
    - images/logos/googleplay_light.png
    - images/logos/windows_store_dark.png
    - images/logos/windows_store_light.png

  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages